# Generated by Django 5.2.3 on 2025-06-19 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_order_delivery_date_order_delivery_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='Bill',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
