# Generated by Django 5.2.3 on 2025-07-14 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Pottery', 'Pottery'), ('Woodcraft', 'Woodcraft'), ('Textiles', 'Textiles'), ('Jewelry', 'Jewelry'), ('Leatherwork', 'Leatherwork'), ('Sculptures', 'Sculptures')], max_length=100),
        ),
    ]
